/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NouveauRouteImport } from './routes/nouveau'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DossierIdRouteImport } from './routes/dossier.$id'

const NouveauRoute = NouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierIdRoute = DossierIdRouteImport.update({
  id: '/dossier/$id',
  path: '/dossier/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nouveau': typeof NouveauRoute
  '/dossier/$id': typeof DossierIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nouveau': typeof NouveauRoute
  '/dossier/$id': typeof DossierIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nouveau': typeof NouveauRoute
  '/dossier/$id': typeof DossierIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nouveau' | '/dossier/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nouveau' | '/dossier/$id'
  id: '__root__' | '/' | '/nouveau' | '/dossier/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NouveauRoute: typeof NouveauRoute
  DossierIdRoute: typeof DossierIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nouveau': {
      id: '/nouveau'
      path: '/nouveau'
      fullPath: '/nouveau'
      preLoaderRoute: typeof NouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier/$id': {
      id: '/dossier/$id'
      path: '/dossier/$id'
      fullPath: '/dossier/$id'
      preLoaderRoute: typeof DossierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NouveauRoute: NouveauRoute,
  DossierIdRoute: DossierIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
